### ISSUE TITLE
Crash calling requestCrafting on AE2 interface

### ISSUE THREAD

**Issue by sci4me** [OpenMods/OpenPeripheral-Integration#10]
http://openeye.openmods.info/crashes/8971be62f618b214270404a6096dd0f8

With this code:
interface.requestCrafting({["id"]="IC2:blockGenerator", ["dmg"]=3}, 512)

**Comment by boq** [comment]
Sorry, we work only with AE2 rv2, while you have rv1.

**Comment by sci4me** [comment]
Aah, good to know. Thanks for the fast reply!
