### ISSUE TITLE
Crafting CPU Name?

### ISSUE THREAD

**Issue by sci4me** [OpenMods/OpenPeripheral-Integration#11]
Crafting CPUs in AE2 can be named? When requesting a crafting job you can specify the name of the CPU you want to use... how do you name a CPU? Right now all mine are named an empty string...

not useful if you can't make then different :P

**Comment by boq** [comment]
After digging in ARE2 code: looks like every building part in AE2 can be named as item (in anvil). Crafting multiblock, when formed, will select one of names as its own. No idea if it actually works.

**Comment by sci4me** [comment]
Aah... interesting. Will try it. Thanks!
