### ISSUE TITLE
AE2 to computercraft request

### ISSUE THREAD

**Issue by masonpinder** [OpenMods/OpenPeripheral-Integration#12]
Is there any easy way to make comoutercraft be able to access an AE network? Also, make it so that it can create "fake" crafting recipes into the AE system, where you specify the item that it looks like, and the name that it shows up as. Possibly making it possible to read from a file for extra textures?

**Comment by boq** [comment]
a) Uh, what do you mean? It's already possible. You mean any particular feature?
b) Out of scope of this project. Also, limited use. And may be just impossible.

**Comment by boq** [comment]
Old issue, closing.
