### ISSUE TITLE
cannot read bees properly, Forestry API deprecated isIrregularMating()

### ISSUE THREAD

**Issue by Xelat84** [OpenMods/OpenPeripheral-Integration#16]
Forestry API deprecated IBee.isIrregularMating(), as described here:
ForestryMC/ForestryAPI@2ad2ee6

So when trying to get information about bee item, it causes error: "forestry.api.apiculture.IBee.isIrregularMating()Z"

**Comment by boq** [comment]
Note: this wasn't caused by deprecation (which does not remove method), but by [this](https://github.com/ForestryMC/ForestryAPI/commit/ad56526b55a42cd44352f8d844564b5e8554c7b3) commit.
