### ISSUE TITLE
pushItems into pipe?

### ISSUE THREAD

**Issue by Nathan1852** [OpenMods/OpenPeripheral-Integration#17]
Would it be possible that the pushItems method could push Into Buildcraft or EnderIo pipes?

**Comment by boq** [comment]
IIRC it should already work with BC pipes (maybe just with wooden pipe?).

**Comment by Nathan1852** [comment]
Sadly not. I tested it with TE Itemducts, EnderIOs Item pipes and a wooden and golden Buildcraft pipe. None of them worked

**Comment by nevercast** [comment]
Which inventory are you pushing from? 
Also versions of OPI/OPC/OML ?

**Comment by Nathan1852** [comment]
I tried to push from a chest

OPI version:  1.7.10-03-snapshot-76
OPC version: 1.7.10-1.2-snapshot-247
OML-1.7.10-0.8-snapshot-382

**Comment by boq** [comment]
Code for pushing to pipes is already there, but I accidentally made [this check](https://github.com/OpenMods/OpenPeripheral-Integration/blob/master/src/main/java/openperipheral/integration/vanilla/AdapterWorldInventory.java#L97) too restrictive.

**Comment by nevercast** [comment]
Sounds like you are on top of that.

**Comment by Nathan1852** [comment]
Any news on this issue?
