### ISSUE TITLE
RC boiler firebox isFormed()?

### ISSUE THREAD

**Issue by Deadlock989** [OpenMods/OpenPeripheral-Integration#18]
Hi,

Love this mod. Having a lot of fun with it

Would it be possible to expose the function that says whether a Railcraft boiler is fully formed, similar to the one available for Big Reactors? I'm suspecting that this method is in there somewhere because WAILA shows an "Is formed: yes/no" tooltip when you look at a firebox.

**Comment by boq** [comment]
Hmm, looks like this is added by "WAILA Plugins", but it's not something I can get from public API (only by linking against mod), so, unfortunately, I have to say 'no'.

**Comment by Deadlock989** [comment]
Oh well. Thanks for looking into it
