### ISSUE TITLE
IC2 Energystorage devices no longer peripherals.

### ISSUE THREAD

**Issue by chrisbecke** [OpenMods/OpenPeripheral-Integration#20]
Forum posts indicate that previously the IC2 energy storage devices - MFSU, MFE, BatBox and the other one - were made into peripherals by OpenPeripherals and thus would connect to a CC modem.

While I can connect (right click to place) a CC wired modem onto other IC2 devices including the nuclear reactor and reactor chambers, I cannot physically place a modem by shift right clicking on a MFSU - or any other of the EU storage devices.

Was support for this dropped?

FTB's direwolf20 1.8.0 has
OpenPeripheralIntegration-1.7.10-0.3.jar
industrialcraft-2-2.770-experimental.jar

**Comment by boq** [comment]
We never added integration for specific blocks. But integration with any block supporting IC2 API is still in there.

Problem lies between IC2 and CC: modems can't be placed on non-solid blocks, but it looks like IC2 energy storage blocks is marked as such.

Proxy block from OpenPeripheral-Addons was created specifically for such occasions. Just place it between modem and any block that refuses to cooperate.
