### ISSUE TITLE
NoteBetter

### ISSUE THREAD

**Issue by SoniEx2** [OpenMods/OpenPeripheral-Integration#21]
NoteBetter is a mod that adds JSON to vanilla note blocks. https://github.com/eNByeX/NoteBetter

**Comment by boq** [comment]
No idea what you want, closing.

**Comment by SoniEx2** [comment]
Well I want NoteBetter compatibility in the vanilla note block integration.

**Comment by boq** [comment]
So describe what you require. Here's our code: https://github.com/OpenMods/OpenPeripheral-Integration/blob/master/src/main/java/openperipheral/integration/vanilla/AdapterNoteBlock.java
