### ISSUE TITLE
Forestry API Changes for Bee Mutations

### ISSUE THREAD

**Issue by ken-noland** [OpenMods/OpenPeripheral-Integration#24]
Hello,

I'm currently running OpenPeripheral-Integrations version 0.5 and Forestry 4.2.11. In Forestry 4.2.0 they changed the getAllele0() and getAllele1() to getSpecies0() and getSpecies1() respectively. Would it be possible to make this change and update the lines on AdapterBeeHousing.java?

Here's a link to the changeset in Forestry: https://github.com/ForestryMC/ForestryAPI/commit/73da80bca5efde424a2a8921985ce919bc6ef0dd

And the followup commit:
https://github.com/ForestryMC/ForestryAPI/commit/87d0201ad926ad9d5c06a7181aaabe3587a5b97a

Cheers,
-Ken

**Comment by ken-noland** [comment]
Nevermind: https://builds.openmods.info/job/OpenPeripheralIntegration/88/changes

**Comment by ken-noland** [comment]
Sorry, didn't fully read the changeset before closing this. The changes made do reflect some API changes, but not to the function calls mentioned

**Comment by boq** [comment]
Well, both options were [valid at some point](https://github.com/ForestryMC/ForestryAPI/commits/master/forestry/api/genetics/IMutation.java).

Anyway, should be fine with recent versions: https://openmods.info/opi-compat.html

**Comment by ken-noland** [comment]
Yup, updated to integrations snapshot 89 and it worked. Sorry about that, newbie issue.
